# This is a default site configuration which will simply return 404, preventing
# chance access to any other virtualhost.

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    client_max_body_size 200m;
    error_page 500 502 503 504 /50x.html;

    location / {
        root /var/lib/nginx/html;
        index index.php index.html index.htm;
    }

    location ~ \.php$ {
        root /var/lib/nginx/html;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location = /50x.html {
        root /var/lib/nginx/html;
    }

    # You may need this to prevent return 404 recursion.
    location = /404.html {
        internal;
    }
}